### ISSUE TITLE
Detect Duplicate Video

### ISSUE THREAD

**Issue by muzavan** [SrikarKSV/MultiTube#1]
First of all, love this project!
 
I tested the platform and I see that currently, you are showing all valid videos inputted. I was wondering, why do you not just showing the unique videos instead?

Also, if you think this is something that legit to implement, I can raise a PR :) 

Thank you!

**Comment by SrikarKSV** [comment]
This is something I'm working on right now!

I would like your opinion here, do you think I should inform the user that we didn't render a video/playlist/channel because it has already been provided?

**Comment by muzavan** [comment]
I think so. A simple alert would do the job. Also, it would be nice if you can highlight which frame contains the duplicate videos.

**Comment by SrikarKSV** [comment]
I'm planning on showing a alert window with the duplicate links, like when wrong links are entered, when duplicate links are entered to follow the pattern of the app.

**Comment by SrikarKSV** [comment]
This feature has been added in the latest commit https://github.com/SrikarKSV/MultiTube/commit/a7ed6d2d729e0b6a203ce197a59d3ecb0db364c4. Now users are alerted when duplicate links are entered.

**Comment by muzavan** [comment]
Neat! I am clossing this issue then. Thanks!
